---
distro_package_command: apt
distro_specific_deps:
  - alien
  - gcc
  - git
  - librsvg2-2
  - libssl-dev
  - libxslt1-dev
  - make
  - python-bugzilla
  - python-dateutil
  - python-dmidecode
  - python-ethtool
  - python-iniparse
  - python-m2crypto
  - python-nose
  - python-pip
  - python-rpm

distro_specific_subman_build_deps:
  - desktop-file-utils
  - distro-info
  - gettext
  - intltool
  - libdbus-glib-1-dev
  - libgconf2-dev
  - libgtk-3-dev
  - libnotify-dev
  - libssl-dev
  - lsb-release
  - python-dev
  - python-setuptools
  - python-six
  - scrollkeeper
